### ISSUE TITLE
DNS event arguments error

### ISSUE THREAD

**Issue by keithjjones** [zeek/spicy-analyzers#10]
On Zeek v4.0.0 I get this error with the current master in cluster mode:

```
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   reporter
#open   2021-03-09-16-41-42
#fields ts      level   message location
#types  time    enum    string  string
1615326102.956359       Reporter::ERROR Event parameter mismatch, expected 6 parameters, but got 5      /Users/keith.jones/.zkg/clones/package/spicy-analyzers/analyzer/protocol/dns/dns.evt, line 17
1615326121.433034       Reporter::ERROR Event parameter mismatch, expected 6 parameters, but got 5      /Users/keith.jones/.zkg/clones/package/spicy-analyzers/analyzer/protocol/dns/dns.evt, line 17
1615326121.434854       Reporter::ERROR Event parameter mismatch, expected 6 parameters, but got 5      /Users/keith.jones/.zkg/clones/package/spicy-analyzers/analyzer/protocol/dns/dns.evt, line 17
1615326124.872783       Reporter::ERROR Event parameter mismatch, expected 6 parameters, but got 5      /Users/keith.jones/.zkg/clones/package/spicy-analyzers/analyzer/protocol/dns/dns.evt, line 17
```
I get similar errors with other versions of Zeek and other protocols (other than wireguard because it's new) in this repo.  I assume one would have to disable the original DNS analyzer to use the new DNS events?  I thought the new dns events would be in a different namespace, but it's causing a conflict with the original ones.  Thanks!

**Comment by keithjjones** [comment]
Thanks for the reply @rsmmr.  

I've installed this in two places (three total installs) with similar results.  1) On a macos macbook with Big Sur. That's the log you see above.  I took zeek v4.0, compiled and installed in cluster mode.  I then compiled and installed spicy.  I then zkg installed spicy-analyzers and I get this error in this issue after I deploy the cluster.  It errors on its own on dns traffic, I don't have to send anything special through.

In scenario 2 I have this installed on 2 identical Linux appliances with Zeek v3.0.2. I compiled spicy on the appliance with all the latest flex+bison+cmake+gcc and I get this same error.  The appliance also says there are the wrong number of arguments and seems to have the original analyzer events loaded as well.

In all cases when I comment out in the cmake file the new spicy analyzers that conflict with the original ones in Zeek, the problems go away.  

I'm happy to produce any debug info if you need it.  Just tell me what you'd like to see.  I look forward to playing with this package more and hopefully contributing a few analyzers.  Thanks!

**Comment by 0xxon** [comment]
In suspicions...

the event that it seems to complain about is dns_request. That is one of the few events where an overloaded variant exists - there is an event with 5 and one with 6 parameters.

Could that lead to this error?

**Comment by keithjjones** [comment]
That sounds right.  Note that I disabled dns and recompiled and saw similar errors in.... I think it was HTTP... so then I just disabled all the ones there was an original analyzer for and kept Wireguard because I was only interested in that one for my project.  Let me know if you need me to pull any info for you, I'm happy to do so on the Linux or Mac systems.  Thanks!

**Comment by jsiwek** [comment]
For Zeek 3.2+, all generated `dns_request` events need to supply 6 parameters (it's valid to *handle* with only 5, but not *generate*):

https://github.com/zeek/zeek/blob/40de20798d668ba77bb87190b3cf90c8739f0fba/src/analyzer/protocol/dns/events.bif#L52-L53

The Spicy analyzer only emits 5:

https://github.com/zeek/spicy-analyzers/blob/d45f6a31e0f99bfbee1bec1a2d948c0c09dc9d19/analyzer/protocol/dns/dns.evt#L16-L17

It might help to get more details on what the HTTP errors were since the Spicy analyzer seems to already try to account for this type of thing:

https://github.com/zeek/spicy-analyzers/blob/d45f6a31e0f99bfbee1bec1a2d948c0c09dc9d19/analyzer/protocol/http/http.evt#L24-L30

**Comment by keithjjones** [comment]
I loaded it on my Linux appliance with Zeek v3.0.2.  This comes up:

```
Mar 11 04:11:09 notice bro-worker-29[2459]: 1615464669.809300 analyzer error in /var/lib/bro-pkg/corelight/state/clones/package/spicy-analyzers/analyzer/protocol/http/http.spicy, line 123: cannot parse bytes as unsigned integer
```

I'll post more if I see them.  I'm running all of them except spicy_dns.

**Comment by keithjjones** [comment]
Another one, but this looks related to spicy proper:

```
Mar 11 04:23:12 notice bro-worker-02[2014]: 1615465392.067997 analyzer error in /data/spicy_install/spicy/share/spicy/filter.spicy, line 11: inflate failed
```

**Comment by keithjjones** [comment]
Another one:

```
Mar 11 04:53:01 notice bro-worker-22[1926]: 1615467181.190726 analyzer error in [REDACTED]/package/spicy-analyzers/analyzer/protocol/http/zeek_http.spicy, line 12: unset optional value
```

**Comment by rsmmr** [comment]
Ah, I must have looked at the wrong version of the DNS event, I'll check it out.

For HTTP, that's very helpful, I'll look at that as well. Any idea if Zeek's standard HTTP parser is parsing these all without hiccups?

Btw, support coming for disabling individual analyzers: https://github.com/zeek/spicy-plugin/pull/4

**Comment by keithjjones** [comment]
Was that everything you all needed?  I had to pull spicy off the real networks to move on to another thing, but if I get time to load it back up I'll be happy to test again.  Let me know.  Thanks!

**Comment by rsmmr** [comment]
Reopening for the HTTP issues. Just took at look at those:

> line 12: unset optional value

I'm going to push a change that I believe should fix this.

> line 123: cannot parse bytes as unsigned integer
> line 11: inflate failed

For these two I can't see anything obviously wrong, would need a trace to track it down (or maybe see the output of Zeek's standard analyzer). One explanation would be just weird traffic of course.

I'm wondering what output Sppicy could produce to make things like this easier to track down. if the error messages contained the relevant excerpt for the traffic, that would be very helpful obviously, but not sure how to define "relevant" and avoid buffering a bunch of stuff. I'll mull over that a bit.

Closing this for now, if more stuff shows up, please open a new ticket.
