### ISSUE TITLE
Zeek scripts don't get installed

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy-analyzers#31]
From Slack: "make install" doesn't do anything with the Zeek scripts. 

I’m wondering where they should go, though. The old instructions suggested to copy them into zeek/site, but I’m not sure  that “make install” should write in there.  Maybe we could do it like with the HLTO files: They land in <prefix>/lib/spicy/zeek and the plugin knows to look there. We could install the scripts somewhere there as well and have the plugin add that to Zeek’s search path automatically.

**Comment by bbannier** [comment]
This will also need some adjustment for the `standalone_ci` CI step so it actually uses the installed files, not the ones from the local checkout.
