### ISSUE TITLE
Sinks in spicy

### ISSUE THREAD

**Issue by ckmk14** [zeek/spicy-analyzers#86]
Hi all,

I have a question w.r.t. to the Sink mechanism.

Suppose I have a protocol based on TCP that looks like this (just for illustration):
```
  1 byte    1 byte    
+--------+-----------+---------+
| length | isChunked | payload |
+--------+-----------+---------+

length:    The length of the payload field in byte
isChunked: The message field is chunked/fragmented into multiple packets
payload:   The payload field
```
Assuming the protocol defines that the payload field consists of three uint8 types, my grammar currently looks like this: 
```
module Test;

public type Messages = unit {
	: Message[];
};

public type Message = unit {
    length:     uint8;                 
    isChunked:  bytes &size=1; 
    payload:    bytes &size=cast<uint64>(self.length) {self.content.write($$);}

    sink content;
    on %init{ self.content.connect(new Payload); }
    on %done { print self; }
};

public type Payload = unit {
        one:    uint8;
        two:    uint8;
        three:   uint8;
};
```
Testing this grammar with:
```
printf '\003\000\004\004\004' | spicy-driver -p Test::Messages test.spicy) 
```
works as expected, here the output:
```
[$length=3, $isChunked=b"\x00", $payload=b"\x04\x04\x04", $content=<sink>]
```
For the following case my grammar does not work anymore:
```
printf '\001\001\004\001\001\004\001\000\004' | spicy-driver -p Test::Messages test.spicy
```
Here the Output:
```
[$length=1, $isChunked=b"\x01", $payload=b"\x04", $content=<sink>]
[error] terminating with uncaught exception of type spicy::rt::ParseError: parse error: expecting 1 bytes for unpacking value (test.spicy:22:17)
```
Can anyone help me out here?

I thought that the processing of the unit **Payload** would work like this, because the operation **self.content.write($$)** is executed three times.  

Best regards
Markus

**Comment by ckmk14** [comment]
Sorry, to bother again but here is my current workaround (buffering the message using a global variable):
Is that okay?
```
module Test;

global buff: bytes;

public type Messages = unit {
	: Message[];
};

public type Message = unit {
    length:     uint8;                 
    isChunked:  bytes &size=1; 
    payload:    bytes  &size=cast<uint64>(self.length);

    sink content;

    on payload {
        buff += self.payload;
        if (self.isChunked == b"\x00") {
            self.content.connect(new Payload);
            print buff;
            self.content.write(buff);
            buff = b"";  
        }  
    }
};

public type Payload = unit {
        one:    uint8;
        two:    uint8;
        three:  uint8;

          on %done { print self; }
};
```

**Comment by bbannier** [comment]
>     payload:    bytes &size=cast<uint64>(self.length) {self.content.write($$);}
>
> I thought that the processing of the unit Payload would work like this,
> because the operation self.content.write($$) is executed three times.

`payload` is a single `bytes` element, so `write` gets called exactly once, regardless of its `size`.

The protocol you sketched _always_ requires `length=3` since `Payload` expects exactly three bytes; any other message is malformed and rightly rejected with a parse error. A more typical protocol which specifies a length would contain a variable-sized field, e.g.,

```
public type Message = unit {
    length:     uint8;
    isChunked:  bytes &size=1; 
    payload:    bytes &size=cast<uint64>(self.length) { self.content.write($$); }

    sink content;
    on %init{ self.content.connect(new Payload); }
};

public type Payload = unit {
    data: uint8[];  # Consumes all passed data.
};
```

Here the `write` makes `self.length` `bytes` available to `Payload` which then extracts them into the same number of `uint8`s (`uint8` consumes one byte).

**Comment by ckmk14** [comment]
Thanks!
